LOCAL_PATH := $(call my-dir)

ADDITIONAL_DEFAULT_PROPERTIES += \
	persist.system.at-proxy.mode=0 \
	persist.asus.sim1.enabled=true \
	persist.asus.sim2.enabled=true \
	persist.asus.mobile_slot=0 \
	persist.logtool.storage.type=0 \
	persist.logtool.uart=0 \
	persist.logtool.usb.switch=0 \
	persist.logtool.gps.loglv=0 \
	persist.logtool.modem.logging=0 \
	persist.logtool.modem.level=3 \
	persist.logtool.modem.num=5 \
	persist.logtool.modem.bplogsize=0 \
	persist.logtool.audio.logging=0 \
	persist.logtool.modem.cd=0 \
	persist.logtool.logging=0 \
	persist.logtool.cos.logging=0 \
	persist.logtool.pos.logging=0 \
	persist.logtool.ros.logging=0 \
	persist.logtool.touch.logging=0 \
	persist.logtool.touch.logrd=0 \
	persist.logtool.maxcrashlog=13 \
	persist.logtool.upi.loglv=0 \
	persist.logtool.sensor.gravity=0 \
	persist.logtool.crashlogd.en=0 \
	persist.logtool.wifi=0
