#!/system/bin/sh

set -x

printk ()
{
	echo "LogTool-MOS: $1" > /dev/kmsg
}

DATE=`timestamp`
LOGDIR="/cache/logtool/boot"

printk "Check if is the first time booting"
if [ -d "$LOGDIR/mos" ]; then
  printk "First time booting kernel mesg exist"
else
  sleep 10
	printk "wait for 10 seconds..."
  mkdir $LOGDIR
  mkdir $LOGDIR/mos
	printk "Start dump first time booting kernel mesg"
	dmesg > $LOGDIR/mos/mos_first_boot_kmesg.txt
fi
