#!/system/bin/busybox sh
# V1.4.4
# fix the Day counting bug
#

trap "" HUP
LogPath="/sdcard/monkey_logs"

counter=0
echo "-16" > /proc/$$/oom_adj

while [ $counter -ne "300" ]; do
 dateVar="$(/system/bin/busybox expr $(date +%d) + $(/system/bin/busybox expr $(/system/bin/busybox expr $(date +%H)) / 24))"
 out="$(date +[%Y:%m:$dateVar]) $(/system/bin/busybox expr $(/system/bin/busybox expr $(date +%H)) % 24):$(date +%M):$(date +%S)"
 echo "$out ============================= $counter =============================" >> $LogPath/procrank.log
 procrank >> $LogPath/procrank.log

 counter=`/system/bin/busybox expr $counter + 1`
 sleep 300
done

exit 0
